name: Quality Handmade Wood Toys.
favicon: null
layout_spectrum: 0.35653
typography_spectrum: 0.90416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2ece3'
    - '#171c15'
    - '#af6353'
    - '#354542'
    - '#848158'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
